version: '3.8'

services:
  web:
    build: .
    ports:
      - "9292:9292"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=bible_api
      - MYSQL_USER=bible_user
      - MYSQL_PASSWORD=bible_password
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=bible_api
      - MYSQL_USER=bible_user
      - MYSQL_PASSWORD=bible_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.0
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: